[package]
name = "amc"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer"] }
rug = { version = "1.26.0", default-features = false, features = ["float", "gmp-mpfr-sys", "std"] }

[build-dependencies]
lalrpop = "0.21.0"
